/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.danielyvalente.controleestoque;

/**
 *
 * @author devsys-a daniely
 */
public class Interface extends javax.swing.JFrame {

    /**
     * Creates new form FormPrincipal
     */
    public Interface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bntAbrirProdutos = new javax.swing.JButton();
        bntAbrirMovimento = new javax.swing.JButton();
        lblCrontoleEstoque = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");

        bntAbrirProdutos.setFont(new java.awt.Font("Segoe UI", 1, 23)); // NOI18N
        bntAbrirProdutos.setText("Produtos");
        bntAbrirProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntAbrirProdutosActionPerformed(evt);
            }
        });

        bntAbrirMovimento.setFont(new java.awt.Font("Segoe UI", 1, 23)); // NOI18N
        bntAbrirMovimento.setText("Movimento");
        bntAbrirMovimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntAbrirMovimentoActionPerformed(evt);
            }
        });

        lblCrontoleEstoque.setFont(new java.awt.Font("Verdana", 1, 26)); // NOI18N
        lblCrontoleEstoque.setText("Controle Estoque");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(bntAbrirProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(bntAbrirMovimento)
                .addGap(28, 28, 28))
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(lblCrontoleEstoque)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(lblCrontoleEstoque)
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntAbrirProdutos)
                    .addComponent(bntAbrirMovimento))
                .addContainerGap(120, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bntAbrirProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntAbrirProdutosActionPerformed
        // TODO add your handling code here:
        //abre o form produtos
        FormProduto fp = new FormProduto();
        fp.setVisible(true);
    }//GEN-LAST:event_bntAbrirProdutosActionPerformed

    private void bntAbrirMovimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntAbrirMovimentoActionPerformed
        // TODO add your handling code here:
        //abre o form movimento
        FormMovimento fm = new FormMovimento();
        fm.setVisible(true);
    }//GEN-LAST:event_bntAbrirMovimentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntAbrirMovimento;
    private javax.swing.JButton bntAbrirProdutos;
    private javax.swing.JLabel lblCrontoleEstoque;
    // End of variables declaration//GEN-END:variables
}
